apiVersion: v1
kind: List
items:
- apiVersion: v1
  data:
    luigi.json: '{"Port": 3101}'
  kind: ConfigMap
  metadata:
    name: luigi
- apiVersion: v1
  kind: Service
  metadata:
    name: luigi
  spec:
    ports:
    - port: 3101
      protocol: TCP
      targetPort: 3101
    selector:
      name: luigi
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: luigi
    name: luigi
  spec:
    containers:
    - args:
      - run.py
#      - /etc/luigi/luigi.json
      command:
      - python3
      image: docker.io/mfenwickbd/luigi:latest
      imagePullPolicy: Always
      name: luigi
      ports:
      - containerPort: 3101
        protocol: TCP
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/luigi
        name: luigi
    restartPolicy: Always
    schedulerName: default-scheduler
    serviceAccount: luigi
    serviceAccountName: luigi
    terminationGracePeriodSeconds: 30
    volumes:
    - configMap:
        defaultMode: 420
        name: luigi
      name: luigi
